version: '3'

# ============== Variables ==============
vars:

  VERSION:
    sh: cat ./config/version
  GIT_SHA:
    sh: git rev-parse --short HEAD
  BUILD_DATE:
    sh: date -u +'%Y-%m-%dT%H:%M:%SZ'

  # Go build flags with embedded version info
  GO_FLAGS: "-s -w"

  DEV_RUN_FLAGS: ""
  BIN: x-ui
  OUT: ./dist

# ============== Tasks ==============
tasks:

  # Clean Go environment
  clean:
    desc: "Clean Go modules and build artifacts"
    silent: true
    cmds:
      - echo "=== Cleaning Go Environment ==="
      - go mod tidy
      - go clean
      - echo "=== Clean Completed ==="

  # Build binary
  build:
    desc: "Build binary"
    silent: true
    cmds:
      - echo "=== Building Binary ==="
      - |
        go build -ldflags="-s -w" \
        -o "./{{.BIN}}" \
        -v "./main.go"
      - echo "=== Build Completed ==="

  # Build binary
  build-linux:
    desc: "Build binary"
    silent: true
    cmds:
      - echo "=== Building Binary ==="
      - |
        go build -ldflags="-s -w" \
        -o "./{{.BIN}}" \
        -v "./main.go"
      - echo "=== Build Completed ==="

  # Build docker image container
  build-image:
    desc: "Build image docker"
    silent: true
    cmds:
      - echo "=== Building image ==="
      - |
        docker build \
          -t ghcr.io/eterline/3x-ui-forked:{{.VERSION}} \
          -t ghcr.io/eterline/3x-ui-forked:latest \
          --label org.opencontainers.image.title="3x-ui-forked" \
          --label org.opencontainers.image.description="Fork of 3x-ui with custom changes" \
          --label org.opencontainers.image.version="{{.VERSION}}" \
          --label org.opencontainers.image.source="https://github.com/eterline/3x-ui-forked" \
          --label org.opencontainers.image.revision="{{.GIT_SHA}}" \
          --label org.opencontainers.image.created="{{.BUILD_DATE}}" \
          --label org.opencontainers.image.licenses="GPL-3.0" \
          .
      - echo "=== Build Completed ==="

  # Build binary
  run:
    desc: "Run binary"
    silent: true
    cmds:
      - task: build
      - ./{{.BIN}}.exe

  # Build binary
  run:
    desc: "Run binary"
    silent: true
    cmds:
      - task: build
      - ./{{.BIN}}.exe

  build-all:
    desc: "Build binaries for multiple OS/ARCH"
    silent: true
    cmds:
      - echo "=== Building binaries for systems ==="
      - mkdir -p "{{.OUT}}"
      - for:
          matrix:
            OS: ['windows', 'linux']
            ARCH: ['amd64']
        cmd: |
          echo "Build for -> {{.ITEM.OS}}/{{.ITEM.ARCH}}: {{.BIN}}-{{.ITEM.OS}}-{{.ITEM.ARCH}}{{if eq .ITEM.OS "windows"}}.exe{{end}}" && \
          GOOS={{.ITEM.OS}} GOARCH={{.ITEM.ARCH}} CGO_ENABLED={{if eq .ITEM.OS "windows"}}0{{else}}1{{end}} \
          go build -trimpath -ldflags="{{.GO_FLAGS}}" \
          -o "./{{.OUT}}/{{.BIN}}-{{.ITEM.OS}}-{{.ITEM.ARCH}}{{if eq .ITEM.OS "windows"}}.exe{{end}}" \
          -v "./main.go"
      - echo "=== Building binaries completed ==="